### ISSUE TITLE
Doesn't insert inplace

### ISSUE THREAD

**Issue by zetas** [julianlam/nodebb-plugin-xkcd-embed#2]
with nodebb 0.7.x when you use the tag for this plugin it inserts the comic at the bottom of the post regardless of where the tag is. Additionally it does not remove the tag. 

so (xkcd#202) remains in the post half way through and the comic image/link is all the way at the bottom.

**Comment by julianlam** [comment]
Hey @zetas -- to my knowledge, this is how the plugin was always handling the embeds (shown in a single block along the bottom), but I'll update it so you can select between the two methods

**Comment by zetas** [comment]
Ah ok, every other embed plugin (except gyfcat) seems to insert the parsed object at the point of trigger so I thought it might be a bug.

**Comment by julianlam** [comment]
No worries, I'm almost done :smile:

**Comment by julianlam** [comment]
You should be able to select the insertion format in the ACP page for this plugin now.
