### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by zetas** [julianlam/nodebb-plugin-xkcd-embed#3]
Using this plugin breaks HTTPS on my site as it pulls images from http://imgs.xkcd.com. 

I looked into the code and I see you're getting that URL from the json webservice. Is there some way to do a string replace or something in the code to swap out http for https? I've already tested visiting the equivalent url in a browser in https and it works fine.

**Comment by julianlam** [comment]
Yeah, this is no problem, I'll switch it over to scheme relative urls in a bit.

**Comment by zetas** [comment]
Great! Thanks.
